#!/usr/bin/env python3
"""CLI for mcp_config MCP server.

Generated by: fastmcp generate-cli D:/Projects/Hermes/hands/mcp_config.json
"""

import json
import sys
from typing import Annotated

import cyclopts
import mcp.types
from rich.console import Console

from fastmcp import Client

# Modify this to change how the CLI connects to the MCP server.
CLIENT_SPEC = {'mcpServers': {'hands': {'command': 'C:\\Python314\\python.exe', 'args': ['D:/Projects/Hermes/hands/server.py']}}}

app = cyclopts.App(name="mcp_config", help="CLI for mcp_config MCP server")
call_tool_app = cyclopts.App(name="call-tool", help="Call a tool on the server")
app.command(call_tool_app)

console = Console()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _print_tool_result(result):
    if result.is_error:
        for block in result.content:
            if isinstance(block, mcp.types.TextContent):
                console.print(f"[bold red]Error:[/bold red] {block.text}")
            else:
                console.print(f"[bold red]Error:[/bold red] {block}")
        sys.exit(1)

    if result.structured_content is not None:
        console.print_json(json.dumps(result.structured_content))
        return

    for block in result.content:
        if isinstance(block, mcp.types.TextContent):
            console.print(block.text)
        elif isinstance(block, mcp.types.ImageContent):
            size = len(block.data) * 3 // 4
            console.print(f"[dim][Image: {block.mimeType}, ~{size} bytes][/dim]")
        elif isinstance(block, mcp.types.AudioContent):
            size = len(block.data) * 3 // 4
            console.print(f"[dim][Audio: {block.mimeType}, ~{size} bytes][/dim]")


async def _call_tool(tool_name: str, arguments: dict) -> None:
    # Filter out None values and empty lists (defaults for optional array params)
    filtered = {
        k: v
        for k, v in arguments.items()
        if v is not None and (not isinstance(v, list) or len(v) > 0)
    }
    async with Client(CLIENT_SPEC) as client:
        result = await client.call_tool(tool_name, filtered, raise_on_error=False)
        _print_tool_result(result)
        if result.is_error:
            sys.exit(1)


# ---------------------------------------------------------------------------
# List / read commands
# ---------------------------------------------------------------------------


@app.command
async def list_tools() -> None:
    """List available tools."""
    async with Client(CLIENT_SPEC) as client:
        tools = await client.list_tools()
        if not tools:
            console.print("[dim]No tools found.[/dim]")
            return
        for tool in tools:
            sig_parts = []
            props = tool.inputSchema.get("properties", {})
            required = set(tool.inputSchema.get("required", []))
            for pname, pschema in props.items():
                ptype = pschema.get("type", "string")
                if pname in required:
                    sig_parts.append(f"{pname}: {ptype}")
                else:
                    sig_parts.append(f"{pname}: {ptype} = ...")
            sig = f"{tool.name}({', '.join(sig_parts)})"
            console.print(f"  [cyan]{sig}[/cyan]")
            if tool.description:
                console.print(f"    {tool.description}")
            console.print()


@app.command
async def list_resources() -> None:
    """List available resources."""
    async with Client(CLIENT_SPEC) as client:
        resources = await client.list_resources()
        if not resources:
            console.print("[dim]No resources found.[/dim]")
            return
        for r in resources:
            console.print(f"  [cyan]{r.uri}[/cyan]")
            desc_parts = [r.name or "", r.description or ""]
            desc = " — ".join(p for p in desc_parts if p)
            if desc:
                console.print(f"    {desc}")
        console.print()


@app.command
async def read_resource(uri: Annotated[str, cyclopts.Parameter(help="Resource URI")]) -> None:
    """Read a resource by URI."""
    async with Client(CLIENT_SPEC) as client:
        contents = await client.read_resource(uri)
        for block in contents:
            if isinstance(block, mcp.types.TextResourceContents):
                console.print(block.text)
            elif isinstance(block, mcp.types.BlobResourceContents):
                size = len(block.blob) * 3 // 4
                console.print(f"[dim][Blob: {block.mimeType}, ~{size} bytes][/dim]")


@app.command
async def list_prompts() -> None:
    """List available prompts."""
    async with Client(CLIENT_SPEC) as client:
        prompts = await client.list_prompts()
        if not prompts:
            console.print("[dim]No prompts found.[/dim]")
            return
        for p in prompts:
            args_str = ""
            if p.arguments:
                parts = [a.name for a in p.arguments]
                args_str = f"({', '.join(parts)})"
            console.print(f"  [cyan]{p.name}{args_str}[/cyan]")
            if p.description:
                console.print(f"    {p.description}")
        console.print()


@app.command
async def get_prompt(
    name: Annotated[str, cyclopts.Parameter(help="Prompt name")],
    *arguments: str,
) -> None:
    """Get a prompt by name. Pass arguments as key=value pairs."""
    parsed: dict[str, str] = {}
    for arg in arguments:
        if "=" not in arg:
            console.print(f"[bold red]Error:[/bold red] Invalid argument {arg!r} — expected key=value")
            sys.exit(1)
        key, value = arg.split("=", 1)
        parsed[key] = value

    async with Client(CLIENT_SPEC) as client:
        result = await client.get_prompt(name, parsed or None)
        for msg in result.messages:
            console.print(f"[bold]{msg.role}:[/bold]")
            if isinstance(msg.content, mcp.types.TextContent):
                console.print(f"  {msg.content.text}")
            elif isinstance(msg.content, mcp.types.ImageContent):
                size = len(msg.content.data) * 3 // 4
                console.print(f"  [dim][Image: {msg.content.mimeType}, ~{size} bytes][/dim]")
            else:
                console.print(f"  {msg.content}")
            console.print()


# ---------------------------------------------------------------------------
# Tool commands (generated from server schema)
# ---------------------------------------------------------------------------

@call_tool_app.command(name='list_windows')
async def list_windows(
    *,
    filter: Annotated[str, cyclopts.Parameter(help="")] = '',
) -> None:
    '''Enumerate visible windows: title, window handle, and rect. Pass a filter (partial title) to narrow.'''
    await _call_tool('list_windows', {'filter': filter})


@call_tool_app.command(name='inspect_window')
async def inspect_window(
    *,
    title: Annotated[str, cyclopts.Parameter(help="")],
    depth: Annotated[int, cyclopts.Parameter(help="")] = 3,
    max_controls: Annotated[int, cyclopts.Parameter(help="")] = 100,
) -> None:
    '''Inspect the UIA control tree of a window (by title, partial match). Returns structured controls with their name, control_type, automation_id, class, and rect. depth limits recursion. This is the structured \'eyes\' — no vision model needed.'''
    await _call_tool('inspect_window', {'title': title, 'depth': depth, 'max_controls': max_controls})


@call_tool_app.command(name='click_element')
async def click_element(
    *,
    title: Annotated[str, cyclopts.Parameter(help="")],
    name: Annotated[str, cyclopts.Parameter(help="")] = '',
    automation_id: Annotated[str, cyclopts.Parameter(help="")] = '',
    button: Annotated[str, cyclopts.Parameter(help="")] = 'left',
) -> None:
    '''Click a UI element in a window by name or automation_id. UIA-first: finds the control in the accessibility tree and clicks it — no pixel guessing. Pass title (window, partial) and either name or automation_id. Optional button (left/right/double).'''
    await _call_tool('click_element', {'title': title, 'name': name, 'automation_id': automation_id, 'button': button})


@call_tool_app.command(name='type_text')
async def type_text(
    *,
    title: Annotated[str, cyclopts.Parameter(help="")],
    text: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    '''Type text into the active/focused control of a window (by title). Text is sent literally (paths, punctuation safe).'''
    await _call_tool('type_text', {'title': title, 'text': text})


@call_tool_app.command(name='navigate_to')
async def navigate_to(
    *,
    title: Annotated[str, cyclopts.Parameter(help="")],
    path: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    '''Navigate a File Explorer window to a folder path. Uses the address bar Edit control directly (set text + Enter) — deterministic, no mouse/focus hunting. Pass title (window, partial) and path (e.g. C:\\Users\\User\\Pictures).'''
    await _call_tool('navigate_to', {'title': title, 'path': path})


@call_tool_app.command(name='press_key')
async def press_key(
    *,
    keys: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    '''Send keyboard hotkeys to the active window. Accepts pywinauto syntax (\'^c\' for ctrl+c, \'%{TAB}\' for alt+tab, \'{ENTER}\') OR plain names (\'ctrl+c\', \'ctrl+x\', \'ctrl+v\', \'alt+tab\', \'enter\', \'esc\'). Prefer the plain-name form — the caret \'^\' can be eaten by the shell layer.'''
    await _call_tool('press_key', {'keys': keys})


@call_tool_app.command(name='mouse_click')
async def mouse_click(
    *,
    x: Annotated[int, cyclopts.Parameter(help="")],
    y: Annotated[int, cyclopts.Parameter(help="")],
    button: Annotated[str, cyclopts.Parameter(help="")] = 'left',
) -> None:
    '''Move the mouse to absolute screen coordinates and click. Uses SendInput (same low-level input as OpenAI Computer Use). Coordinates are in native screen pixels: x,y from the top-left of the primary monitor. Optional button: left/right/double. Refuses to click ELEVATED windows (UIPI silently blocks them — reports honestly instead).'''
    await _call_tool('mouse_click', {'x': x, 'y': y, 'button': button})


@call_tool_app.command(name='mouse_position')
async def mouse_position(
) -> None:
    '''Return the current cursor position in screen pixels (GetCursorPos). Cheap verification for where the mouse actually is.'''
    await _call_tool('mouse_position', {})


@call_tool_app.command(name='scroll')
async def scroll(
    *,
    clicks: Annotated[int, cyclopts.Parameter(help="")],
    x: Annotated[int, cyclopts.Parameter(help="")] = -1,
    y: Annotated[int, cyclopts.Parameter(help="")] = -1,
) -> None:
    '''Scroll the mouse wheel at the current cursor position. Positive clicks scroll up (away from user), negative scrolls down. e.g. scroll(3) scrolls up 3 notches, scroll(-5) scrolls down 5.'''
    await _call_tool('scroll', {'clicks': clicks, 'x': x, 'y': y})


@call_tool_app.command(name='drag')
async def drag(
    *,
    x1: Annotated[int, cyclopts.Parameter(help="")],
    y1: Annotated[int, cyclopts.Parameter(help="")],
    x2: Annotated[int, cyclopts.Parameter(help="")],
    y2: Annotated[int, cyclopts.Parameter(help="")],
    button: Annotated[str, cyclopts.Parameter(help="")] = 'left',
    steps: Annotated[int, cyclopts.Parameter(help="")] = 10,
) -> None:
    '''Drag from (x1,y1) to (x2,y2): press the button at the start, move through the path, release at the end. Coordinates are virtual-desktop (multi-monitor safe). Optional button: left/right.'''
    await _call_tool('drag', {'x1': x1, 'y1': y1, 'x2': x2, 'y2': y2, 'button': button, 'steps': steps})


@call_tool_app.command(name='get_clipboard')
async def get_clipboard(
) -> None:
    '''Read the current clipboard text. Use to verify a copy/cut actually captured content before pasting.'''
    await _call_tool('get_clipboard', {})


@call_tool_app.command(name='set_clipboard')
async def set_clipboard(
    *,
    text: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    '''Set the clipboard to text. Use before a deterministic paste when you need known content on the clipboard.'''
    await _call_tool('set_clipboard', {'text': text})


@call_tool_app.command(name='move_file')
async def move_file(
    *,
    source: Annotated[str, cyclopts.Parameter(help="")],
    destination: Annotated[str, cyclopts.Parameter(help="")],
    copy: Annotated[bool, cyclopts.Parameter(help="")] = False,
) -> None:
    '''Move a file to a destination folder deterministically via copy-then-verify-then-delete — never cut+paste. Copying first means the source survives any failure; the original is only deleted after the copy is verified to exist. Pass source path and destination folder.'''
    await _call_tool('move_file', {'source': source, 'destination': destination, 'copy': copy})


@call_tool_app.command(name='run_command')
async def run_command(
    *,
    command: Annotated[str, cyclopts.Parameter(help="")],
    timeout: Annotated[int, cyclopts.Parameter(help="")] = 30,
) -> None:
    '''Run a PowerShell command and capture output. Use for anything the shell does faster than clicking (create folder, list files, run a script, query services). This is the UFO² hybrid principle: shell beats GUI clicks when it can. For destructive commands (delete, kill, format, registry writes) use run_command_guarded which requires your approval first.'''
    await _call_tool('run_command', {'command': command, 'timeout': timeout})


@call_tool_app.command(name='launch_app')
async def launch_app(
    *,
    target: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    '''Launch a program by path or a start command (app name, file, URL). Uses os.startfile for double-click-equivalent launch.'''
    await _call_tool('launch_app', {'target': target})


@call_tool_app.command(name='focus_window')
async def focus_window(
    *,
    title: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    '''Bring a window to the foreground by title (partial match). Does not move the mouse.'''
    await _call_tool('focus_window', {'title': title})


@call_tool_app.command(name='screenshot')
async def screenshot(
    *,
    mode: Annotated[str, cyclopts.Parameter(help="")] = 'full',
    target: Annotated[str, cyclopts.Parameter(help="")] = '',
) -> None:
    '''Capture the screen (full, window, or region) via the canonical Zoro screenshot script. Returns path for vision analysis.'''
    await _call_tool('screenshot', {'mode': mode, 'target': target})


@call_tool_app.command(name='find_on_screen')
async def find_on_screen(
    *,
    what: Annotated[str, cyclopts.Parameter(help="")],
    window: Annotated[str, cyclopts.Parameter(help="")] = '',
    mode: Annotated[str, cyclopts.Parameter(help="")] = 'full',
) -> None:
    '''Vision-driven element location: screenshot the screen (or a window), ask the local VLM where a described element is, and return approximate pixel coordinates. Use when UIA can\'t identify the control (canvas apps, games, custom UI). Pass what=\'the red Submit button\' or similar. This is the UI-TARS-style fallback.'''
    await _call_tool('find_on_screen', {'what': what, 'window': window, 'mode': mode})


@call_tool_app.command(name='verify_state')
async def verify_state(
    *,
    condition: Annotated[str, cyclopts.Parameter(help="")],
    window: Annotated[str, cyclopts.Parameter(help="")] = '',
    mode: Annotated[str, cyclopts.Parameter(help="")] = 'full',
) -> None:
    '''Vision-driven verification: screenshot the screen/window and ask the local VLM whether a condition is true (e.g. \'is there a green checkmark?\', \'did a dialog open?\', \'is the app running?\'). Returns yes/no + explanation. Use to close the act→verify loop.'''
    await _call_tool('verify_state', {'condition': condition, 'window': window, 'mode': mode})


@call_tool_app.command(name='window_manager_ui')
async def window_manager_ui(
) -> None:
    '''Open the interactive Window Manager app: a searchable/sortable window table where you can FOCUS any window by clicking a button (FastMCP v3 FastMCPApp with UI→server callbacks).'''
    await _call_tool('window_manager_ui', {})


@call_tool_app.command(name='search_tools')
async def search_tools(
    *,
    query: Annotated[str, cyclopts.Parameter(help="Natural language query to search for tools")],
) -> None:
    '''Search for tools using natural language.

Returns matching tool definitions ranked by relevance,
in the same format as list_tools.'''
    await _call_tool('search_tools', {'query': query})


@call_tool_app.command(name='call_tool')
async def call_tool(
    *,
    name: Annotated[str, cyclopts.Parameter(help="The name of the tool to call")],
    arguments: Annotated[str | None, cyclopts.Parameter(help="Arguments to pass to the tool\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"additionalProperties\": true,\n                                \"type\": \"object\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"Arguments to pass to the tool\"\n                          }")] = None,
) -> None:
    '''Call a tool by name with the given arguments.

Use this to execute tools discovered via search_tools.'''
    # Parse JSON parameters
    arguments_parsed = json.loads(arguments) if isinstance(arguments, str) else arguments

    await _call_tool('call_tool', {'name': name, 'arguments': arguments_parsed})


if __name__ == "__main__":
    app()
