#!/usr/bin/env python3
"""CLI for the Zoro Vision FastMCP v3 server.

Generated by: fastmcp generate-cli D:/Projects/Hermes/vision/mcp_config.json
"""

import json
import sys
from typing import Annotated

import cyclopts
import mcp.types
from rich.console import Console

from fastmcp import Client

# Modify this to change how the CLI connects to the MCP server.
CLIENT_SPEC = {'mcpServers': {'vision': {'command': 'C:\\Python314\\python.exe', 'args': ['D:/Projects/Hermes/vision/server.py']}}}

app = cyclopts.App(name="vision", help="CLI for the Zoro Vision FastMCP v3 server")
call_tool_app = cyclopts.App(name="call-tool", help="Call a tool on the server")
app.command(call_tool_app)

console = Console()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _print_tool_result(result):
    if result.is_error:
        for block in result.content:
            if isinstance(block, mcp.types.TextContent):
                console.print(f"[bold red]Error:[/bold red] {block.text}")
            else:
                console.print(f"[bold red]Error:[/bold red] {block}")
        sys.exit(1)

    if result.structured_content is not None:
        console.print_json(json.dumps(result.structured_content))
        return

    for block in result.content:
        if isinstance(block, mcp.types.TextContent):
            console.print(block.text)
        elif isinstance(block, mcp.types.ImageContent):
            size = len(block.data) * 3 // 4
            console.print(f"[dim][Image: {block.mimeType}, ~{size} bytes][/dim]")
        elif isinstance(block, mcp.types.AudioContent):
            size = len(block.data) * 3 // 4
            console.print(f"[dim][Audio: {block.mimeType}, ~{size} bytes][/dim]")


async def _call_tool(tool_name: str, arguments: dict) -> None:
    # Filter out None values and empty lists (defaults for optional array params)
    filtered = {
        k: v
        for k, v in arguments.items()
        if v is not None and (not isinstance(v, list) or len(v) > 0)
    }
    async with Client(CLIENT_SPEC) as client:
        result = await client.call_tool(tool_name, filtered, raise_on_error=False)
        _print_tool_result(result)
        if result.is_error:
            sys.exit(1)


# ---------------------------------------------------------------------------
# List / read commands
# ---------------------------------------------------------------------------


@app.command
async def list_tools() -> None:
    """List available tools."""
    async with Client(CLIENT_SPEC) as client:
        tools = await client.list_tools()
        if not tools:
            console.print("[dim]No tools found.[/dim]")
            return
        for tool in tools:
            sig_parts = []
            props = tool.inputSchema.get("properties", {})
            required = set(tool.inputSchema.get("required", []))
            for pname, pschema in props.items():
                ptype = pschema.get("type", "string")
                if pname in required:
                    sig_parts.append(f"{pname}: {ptype}")
                else:
                    sig_parts.append(f"{pname}: {ptype} = ...")
            sig = f"{tool.name}({', '.join(sig_parts)})"
            console.print(f"  [cyan]{sig}[/cyan]")
            if tool.description:
                console.print(f"    {tool.description}")
            console.print()


@app.command
async def list_resources() -> None:
    """List available resources."""
    async with Client(CLIENT_SPEC) as client:
        resources = await client.list_resources()
        if not resources:
            console.print("[dim]No resources found.[/dim]")
            return
        for r in resources:
            console.print(f"  [cyan]{r.uri}[/cyan]")
            desc_parts = [r.name or "", r.description or ""]
            desc = " — ".join(p for p in desc_parts if p)
            if desc:
                console.print(f"    {desc}")
        console.print()


@app.command
async def read_resource(uri: Annotated[str, cyclopts.Parameter(help="Resource URI")]) -> None:
    """Read a resource by URI."""
    async with Client(CLIENT_SPEC) as client:
        contents = await client.read_resource(uri)
        for block in contents:
            if isinstance(block, mcp.types.TextResourceContents):
                console.print(block.text)
            elif isinstance(block, mcp.types.BlobResourceContents):
                size = len(block.blob) * 3 // 4
                console.print(f"[dim][Blob: {block.mimeType}, ~{size} bytes][/dim]")


@app.command
async def list_prompts() -> None:
    """List available prompts."""
    async with Client(CLIENT_SPEC) as client:
        prompts = await client.list_prompts()
        if not prompts:
            console.print("[dim]No prompts found.[/dim]")
            return
        for p in prompts:
            args_str = ""
            if p.arguments:
                parts = [a.name for a in p.arguments]
                args_str = f"({', '.join(parts)})"
            console.print(f"  [cyan]{p.name}{args_str}[/cyan]")
            if p.description:
                console.print(f"    {p.description}")
        console.print()


@app.command
async def get_prompt(
    name: Annotated[str, cyclopts.Parameter(help="Prompt name")],
    *arguments: str,
) -> None:
    """Get a prompt by name. Pass arguments as key=value pairs."""
    parsed: dict[str, str] = {}
    for arg in arguments:
        if "=" not in arg:
            console.print(f"[bold red]Error:[/bold red] Invalid argument {arg!r} — expected key=value")
            sys.exit(1)
        key, value = arg.split("=", 1)
        parsed[key] = value

    async with Client(CLIENT_SPEC) as client:
        result = await client.get_prompt(name, parsed or None)
        for msg in result.messages:
            console.print(f"[bold]{msg.role}:[/bold]")
            if isinstance(msg.content, mcp.types.TextContent):
                console.print(f"  {msg.content.text}")
            elif isinstance(msg.content, mcp.types.ImageContent):
                size = len(msg.content.data) * 3 // 4
                console.print(f"  [dim][Image: {msg.content.mimeType}, ~{size} bytes][/dim]")
            else:
                console.print(f"  {msg.content}")
            console.print()


# ---------------------------------------------------------------------------
# Tool commands (generated from server schema)
# ---------------------------------------------------------------------------

@call_tool_app.command(name='screenshot')
async def screenshot(
    *,
    mode: Annotated[str, cyclopts.Parameter(help="")] = 'full',
    target: Annotated[str, cyclopts.Parameter(help="")] = '',
    x: Annotated[int, cyclopts.Parameter(help="")] = 0,
    y: Annotated[int, cyclopts.Parameter(help="")] = 0,
    width: Annotated[int, cyclopts.Parameter(help="")] = 0,
    height: Annotated[int, cyclopts.Parameter(help="")] = 0,
    out_name: Annotated[str, cyclopts.Parameter(help="")] = '',
) -> None:
    '''Capture a screenshot of the screen (full desktop, a specific window by title, or a pixel region) and save it. Returns the saved path + size so other vision tools (describe, get_colors, get_layout, read_text) can analyze it. Mode: \'full\' | \'window\' | \'region\'. For window, pass target (partial title match). For region, pass x, y, width, height. Delegates to the canonical Zoro screenshot.py (D:\\Projects\\Zoro\\scripts), saves to ~/.screenshots/.'''
    await _call_tool('screenshot', {'mode': mode, 'target': target, 'x': x, 'y': y, 'width': width, 'height': height, 'out_name': out_name})


@call_tool_app.command(name='get_metadata')
async def get_metadata(
    *,
    image: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    '''Return image dimensions, format, mode, file size, and basic EXIF (orientation, datetime).'''
    await _call_tool('get_metadata', {'image': image})


@call_tool_app.command(name='get_colors')
async def get_colors(
    *,
    image: Annotated[str, cyclopts.Parameter(help="")],
    count: Annotated[int, cyclopts.Parameter(help="")] = 8,
) -> None:
    '''Extract the dominant color palette from an image. Returns top N colors as hex + RGB + approximate percentage coverage. Optionally a named description of each color.'''
    await _call_tool('get_colors', {'image': image, 'count': count})


@call_tool_app.command(name='get_layout')
async def get_layout(
    *,
    image: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    '''Analyze image spatial layout without a model: brightness per region (left/center/right, top/middle/bottom thirds), edge density, and simple composition hints (bright areas, dark areas, centered subject heuristic).'''
    await _call_tool('get_layout', {'image': image})


@call_tool_app.command(name='crop')
async def crop(
    *,
    image: Annotated[str, cyclopts.Parameter(help="")],
    x: Annotated[int, cyclopts.Parameter(help="")],
    y: Annotated[int, cyclopts.Parameter(help="")],
    width: Annotated[int, cyclopts.Parameter(help="")],
    height: Annotated[int, cyclopts.Parameter(help="")],
    out_name: Annotated[str, cyclopts.Parameter(help="")] = '',
) -> None:
    '''Crop an image to a region (x, y, width, height in pixels, 0-based from top-left) and save the result to a work dir. Returns the saved path + size. Optionally pass out_name for a stable filename.'''
    await _call_tool('crop', {'image': image, 'x': x, 'y': y, 'width': width, 'height': height, 'out_name': out_name})


@call_tool_app.command(name='compare')
async def compare(
    *,
    image_a: Annotated[str, cyclopts.Parameter(help="")],
    image_b: Annotated[str, cyclopts.Parameter(help="")],
    threshold: Annotated[float, cyclopts.Parameter(help="")] = 0.85,
) -> None:
    '''Compare two images using perceptual hash (dHash). Returns similarity 0-1 (1 = identical), Hamming distance, and whether they\'re \'same\' (>= threshold).'''
    await _call_tool('compare', {'image_a': image_a, 'image_b': image_b, 'threshold': threshold})


@call_tool_app.command(name='read_text')
async def read_text(
    *,
    image: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    '''OCR an image with the local VLM (qwen3-vl reads text well). Returns the detected text. Prefer this on UI screenshots, covers, text-heavy images.'''
    await _call_tool('read_text', {'image': image})


@call_tool_app.command(name='describe')
async def describe(
    *,
    image: Annotated[str, cyclopts.Parameter(help="")],
    prompt: Annotated[str, cyclopts.Parameter(help="")] = 'Describe this image in detail.',
) -> None:
    '''Semantic understanding of an image via local VLM. Returns a natural-language description. Pass a prompt for a targeted question (e.g. \'What UI elements are in this screenshot?\'). Models tried in order: qwen3-vl:4b, moondream.'''
    await _call_tool('describe', {'image': image, 'prompt': prompt})


@call_tool_app.command(name='palette_ui')
async def palette_ui(
    *,
    image: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    '''Visual color palette UI for an image: rendered swatches + hex codes in an interactive grid (FastMCP v3 Apps).'''
    await _call_tool('palette_ui', {'image': image})


@call_tool_app.command(name='image_inspector')
async def image_inspector(
    *,
    path: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    '''Open the interactive Image Inspector: renders the image with an overlay of detected regions (brightness zones) plus color swatches and layout data side by side (FastMCP v3 Apps).'''
    await _call_tool('image_inspector', {'path': path})


if __name__ == "__main__":
    app()
